apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgresql.yaml
  - kafka.yaml
  - redis.yaml
  - neo4j.yaml
  - openldap.yaml

commonLabels:
  component: infrastructure
