apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-auth-sa
  labels:
    app: circleguard-auth-service
    app.kubernetes.io/component: microservice-rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-identity-sa
  labels:
    app: circleguard-identity-service
    app.kubernetes.io/component: microservice-rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-form-sa
  labels:
    app: circleguard-form-service
    app.kubernetes.io/component: microservice-rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-promotion-sa
  labels:
    app: circleguard-promotion-service
    app.kubernetes.io/component: microservice-rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-notification-sa
  labels:
    app: circleguard-notification-service
    app.kubernetes.io/component: microservice-rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-gateway-sa
  labels:
    app: circleguard-gateway-service
    app.kubernetes.io/component: microservice-rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-file-sa
  labels:
    app: circleguard-file-service
    app.kubernetes.io/component: microservice-rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-dashboard-sa
  labels:
    app: circleguard-dashboard-service
    app.kubernetes.io/component: microservice-rbac
