apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: master

resources:
  - ../base

commonLabels:
  environment: master

images:
  - name: circleguard-auth-service
    newName: srcracles/circleguard-auth-service
    newTag: stage
  - name: circleguard-identity-service
    newName: srcracles/circleguard-identity-service
    newTag: stage
  - name: circleguard-form-service
    newName: srcracles/circleguard-form-service
    newTag: stage
  - name: circleguard-promotion-service
    newName: srcracles/circleguard-promotion-service
    newTag: stage
  - name: circleguard-notification-service
    newName: srcracles/circleguard-notification-service
    newTag: stage
  - name: circleguard-gateway-service
    newName: srcracles/circleguard-gateway-service
    newTag: stage
  - name: circleguard-file-service
    newName: srcracles/circleguard-file-service
    newTag: stage
  - name: circleguard-dashboard-service
    newName: srcracles/circleguard-dashboard-service
    newTag: stage
