sonar.projectKey=circleguard-notification-service
sonar.projectName=CircleGuard Notification Service
sonar.sources=src/main
sonar.tests=src/test
sonar.java.binaries=build/classes
sonar.qualitygate.wait=true
