apiVersion: v1
kind: Service
metadata:
  name: circleguard-file-service
  labels:
    app: circleguard-file-service
spec:
  selector:
    app: circleguard-file-service
  ports:
    - port: 8085
      targetPort: 8085
      name: http
  type: ClusterIP
