apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-form-service
  labels:
    app: circleguard-form-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-form-service
  template:
    metadata:
      labels:
        app: circleguard-form-service
    spec:
      containers:
        - name: circleguard-form-service
          image: srcracles/circleguard-form-service:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: circleguard-config
            - secretRef:
                name: circleguard-secrets
          env:
            - name: SPRING_APPLICATION_NAME
              value: "circleguard-form-service"
