apiVersion: v1
kind: Service
metadata:
  name: circleguard-gateway-service
  labels:
    app: circleguard-gateway-service
spec:
  selector:
    app: circleguard-gateway-service
  ports:
    - port: 8087
      targetPort: 8087
      name: http
  type: ClusterIP
