apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-gateway-service
  labels:
    app: circleguard-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-gateway-service
  template:
    metadata:
      labels:
        app: circleguard-gateway-service
    spec:
      containers:
        - name: circleguard-gateway-service
          image: circleguard-gateway-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8087
          envFrom:
            - configMapRef:
                name: circleguard-config
            - secretRef:
                name: circleguard-secrets
          env:
            - name: SPRING_APPLICATION_NAME
              value: "circleguard-gateway-service"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8087
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8087
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
