apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-identity-service
  labels:
    app: circleguard-identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-identity-service
  template:
    metadata:
      labels:
        app: circleguard-identity-service
    spec:
      containers:
        - name: circleguard-identity-service
          image: srcracles/circleguard-identity-service:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: circleguard-config
            - secretRef:
                name: circleguard-secrets
          env:
            - name: SPRING_APPLICATION_NAME
              value: "circleguard-identity-service"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgresql.infra.svc.cluster.local:5432/circleguard_identity"
