apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac/serviceaccounts.yaml
  - rbac/microservice-roles.yaml
  - rbac/microservice-rolebindings.yaml
  - configmap.yaml
  - auth-deployment.yaml
  - auth-service.yaml
  - identity-deployment.yaml
  - identity-service.yaml
  - form-deployment.yaml
  - form-service.yaml
  - promotion-deployment.yaml
  - promotion-service.yaml
  - notification-deployment.yaml
  - notification-service.yaml
  - gateway-deployment.yaml
  - gateway-service.yaml
  - file-deployment.yaml
  - file-service.yaml
  - dashboard-deployment.yaml
  - dashboard-service.yaml
