apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-promotion-service
  labels:
    app: circleguard-promotion-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-promotion-service
  template:
    metadata:
      labels:
        app: circleguard-promotion-service
    spec:
      containers:
        - name: circleguard-promotion-service
          image: circleguard-promotion-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
          envFrom:
            - configMapRef:
                name: circleguard-config
            - secretRef:
                name: circleguard-secrets
          env:
            - name: SPRING_APPLICATION_NAME
              value: "circleguard-promotion-service"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgresql.infra.svc.cluster.local:5432/circleguard_promotion"
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: "promotion-service-group"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8088
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8088
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 3
