sonar.projectKey=circleguard-promotion-service
sonar.projectName=CircleGuard Promotion Service
sonar.sources=src/main
sonar.tests=src/test
sonar.java.binaries=build/classes
sonar.qualitygate.wait=true
